import { createHash } from 'node:crypto';

const MAX_FAILED_CHECKS = 32;
const MAX_IDENTIFIER_LENGTH = 128;
export const MAX_DIAGNOSTIC_COLLECTION = 256;
export const MAX_DIAGNOSTIC_NUMBER = 1_000_000_000;

const DEFINITIONS = Object.freeze({
  inactive: ['check host prerequisites, then ape_run start', 'No APE run is active; start a run when work is ready.'],
  preflight_input_required: ['ape_run answer-preflight', 'Preflight is waiting for the operator to answer its complete immutable question set.'],
  receipt_retry_input_required: ['continue the same agent and record the exact attested receipt', 'Receipt validation requested a bounded correction from the already-bound worker.'],
  execution_budget_input_required: ['wait for the retained continuation', 'The runtime retained a continuation that must resume through its bounded scheduler path.'],
  dispatch_pending: ['ape_run resume', 'The durable ticket is pending dispatch; resume to relaunch it safely.'],
  dispatch_live: ['wait for pending receipt', 'A live agent owns the pending ticket; wait for its receipt.'],
  dispatch_stopped: ['ape_run resume', 'The native agent stopped before a receipt was recorded; resume to relaunch it safely.'],
  dispatch_evidence_unreadable: ['ape_run abort', 'Durable dispatch evidence is unreadable; abort revokes and quarantines the damaged intent before sealing the run.'],
  stage_active: ['ape_run next', 'The current stage is active and can advance through the scheduler.'],
  gating: ['ape_run next', 'Deterministic gates are running; poll them through the scheduler.'],
  gate_failed: ['ape_run regate', 'A deterministic gate failed; fix the cause and re-run the full gate suite.'],
  blocked: ['ape_run abort or ape_run override reset', 'The run is blocked outside a recoverable gate transition; use an audited exit.'],
  shipping_hold: ['ape_run ship', 'All gates passed and shipping awaits an explicit audited ship action.'],
  shipping: ['ape_run next', 'Shipping is in progress; poll it through the scheduler.'],
  cleanup_pending: ['ape_run resume', 'The run is terminal but checkout cleanup has not returned; resume to finish cleanup safely.'],
  completed: ['check host prerequisites, then ape_run start', 'The run completed and a new run may be started.'],
  aborted: ['check host prerequisites, then ape_run start', 'The run was aborted and a new run may be started.'],
  corrupt_state: ['ape_run override reset', 'The active state cannot be read safely; quarantine it with an audited reset.'],
  incomplete_record: ['inspect immutable history', 'The archived record lacks enough durable lifecycle evidence for a stronger diagnosis.'],
  legacy_record: ['inspect immutable history', 'The imported legacy record does not contain modern diagnostic evidence.'],
});

const UNSAFE_TEXT = /[\u0000-\u001f\u007f-\u009f\u00ad\u061c\u200b-\u200f\u202a-\u202e\u2060-\u206f\ufff9-\ufffb]/g;
const IDENTIFIER = /^[A-Za-z0-9][A-Za-z0-9_.:-]*$/;
const RUN_ID = /^run-[A-Za-z0-9][A-Za-z0-9_-]{0,123}$/;
const ISO = /^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})(?:\.(\d{1,9}))?(Z|([+-])(\d{2}):(\d{2}))$/;
const ENUMS = {
  schema_version: new Set(['2.0.0']),
  mode: new Set(['phase', 'debug', 'spike', 'land']),
  lane: new Set(['auto', 'mechanical', 'fast', 'full']),
  status: new Set(['planning', 'running', 'input_required', 'gating', 'blocked', 'shipping', 'completed', 'aborted']),
  stage: new Set(['plan', 'plan-replan', 'plan-approval', 'preflight', 'plan-check', 'plan-critic', 'plan-judge', 'test', 'test-reconcile', 'test-recheck', 'build', 'implement', 'review', 'security-review', 'remediation', 'remediation-test', 'remediation-build', 'remediation-review', 'remediation-security-review', 'gates', 'merge', 'dispatch', 'start', 'execution-budget', 'complete', 'completed', 'aborted', 'debug', 'spike']),
  host: new Set(['codex', 'claude']),
  dispatch_state: new Set(['pending', 'needs-redispatch', 'live', 'stopped', 'error', 'none']),
};
const MODEL_TIERS = new Set(['fast', 'balanced', 'deep']);
const TICKET_ROLES = new Set(['test_writer', 'implementer', 'reviewer', 'security_reviewer', 'planner', 'preflight_analyst', 'plan_checker', 'plan_critic', 'plan_judge', 'debugger', 'spike_researcher']);
const REF_NAME = /^(?!.*(?:\.\.|\/\/|@\{|[~^:?*[\]\\\s]))(?!\.)(?!.*(?:^|\/)\.)(?!.*\.lock(?:\/|$))(?!.*[/.]$)[A-Za-z0-9][A-Za-z0-9._/-]{0,255}$/;

function diagnosticHashRecord(value, omittedFields) {
  const normalize = (input) => {
    if (Array.isArray(input)) return input.map(normalize);
    if (input && typeof input === 'object') return Object.fromEntries(Object.keys(input).sort().filter((key) => input[key] !== undefined).map((key) => [key, normalize(input[key])]));
    return input;
  };
  const copy = { ...value };
  for (const field of omittedFields) delete copy[field];
  return createHash('sha256').update(JSON.stringify(normalize(copy))).digest('hex');
}

export function safeDiagnosticText(value, max = MAX_IDENTIFIER_LENGTH) {
  if (typeof value !== 'string') return null;
  const flat = value.replace(UNSAFE_TEXT, '').replace(/\s+/g, ' ').trim();
  if (!flat) return null;
  return flat.length > max ? `${flat.slice(0, Math.max(0, max - 1))}…` : flat;
}
function plain(value) { if (!value || typeof value !== 'object' || Array.isArray(value)) return false; const proto = Object.getPrototypeOf(value); return proto === Object.prototype || proto === null; }
function ownData(value, key) { if (!plain(value)) return { ok: false }; const descriptor = Object.getOwnPropertyDescriptor(value, key); if (!descriptor || !('value' in descriptor)) return { ok: false }; return { ok: true, value: descriptor.value }; }
function identifier(value, pattern = IDENTIFIER) { return typeof value === 'string' && value.length <= MAX_IDENTIFIER_LENGTH && pattern.test(value); }
export function isCanonicalRunId(value) { return identifier(value, RUN_ID); }
export function strictIsoMs(value) {
  if (typeof value !== 'string') return null; const match = ISO.exec(value); if (!match) return null;
  const year=Number(match[1]), month=Number(match[2]), day=Number(match[3]), hour=Number(match[4]), minute=Number(match[5]), second=Number(match[6]);
  const offsetHour=match[8]==='Z'?0:Number(match[10]), offsetMinute=match[8]==='Z'?0:Number(match[11]);
  const leap=year%4===0&&(year%100!==0||year%400===0); const days=[0,31,leap?29:28,31,30,31,30,31,31,30,31,30,31][month]??0;
  if(day<1||day>days||hour>23||minute>59||second>59||offsetHour>23||offsetMinute>59)return null; const parsed=Date.parse(value); return Number.isFinite(parsed)?parsed:null;
}
function boundedNumber(value){return typeof value==='number'&&Number.isFinite(value)&&value>=0&&value<=MAX_DIAGNOSTIC_NUMBER;}
function validArray(value,itemValidator=(_item)=>true){if(!Array.isArray(value)||value.length>MAX_DIAGNOSTIC_COLLECTION)return false;for(let i=0;i<value.length;i+=1){const descriptor=Object.getOwnPropertyDescriptor(value,String(i));if(!descriptor||!('value'in descriptor))return false;}for(let i=0;i<value.length;i+=1){if(!itemValidator(Object.getOwnPropertyDescriptor(value,String(i)).value))return false;}return true;}
function boundedOwnDataKeys(value,max=MAX_DIAGNOSTIC_COLLECTION){if(!plain(value))return null;const keys=[];for(const key in value){if(!Object.hasOwn(value,key))continue;if(keys.length===max)return null;const descriptor=Object.getOwnPropertyDescriptor(value,key);if(!descriptor||!('value'in descriptor))return null;keys.push(key);}if(Object.getOwnPropertySymbols(value).length>0)return null;return keys;}
export function isValidMergeEvidence(merge){
  if(!plain(merge))return false;const allowed=new Set(['provider','url','branch','base','merged_at','provenance','sha','method']);const keys=boundedOwnDataKeys(merge,allowed.size);if(!keys||keys.some((key)=>!allowed.has(key)))return false;
  if(ownData(merge,'provider').value!=='github')return false;for(const key of ['url','branch','base']){const value=ownData(merge,key).value;if(typeof value!=='string'||value.length===0||value.length>2048||safeDiagnosticText(value,2048)!==value)return false;}
  try{const parsed=new URL(ownData(merge,'url').value);if(parsed.protocol!=='https:'||parsed.username||parsed.password||parsed.hostname.toLowerCase()!=='github.com'||parsed.port||parsed.search||parsed.hash)return false;}catch{return false;}
  if(!REF_NAME.test(ownData(merge,'branch').value)||!REF_NAME.test(ownData(merge,'base').value))return false;if(strictIsoMs(ownData(merge,'merged_at').value)===null)return false;
  const provenance=ownData(merge,'provenance').value;if(provenance!==undefined&&provenance!=='observed-external')return false;const method=ownData(merge,'method').value;if(method!==undefined&&!['merge','rebase','squash'].includes(method))return false;const sha=ownData(merge,'sha').value;if(sha!==undefined&&(typeof sha!=='string'||!/^[0-9a-f]{40}(?:[0-9a-f]{24})?$/i.test(sha)))return false;return true;
}
export function safeModelTier(value){return MODEL_TIERS.has(value)?value:null;}
function plainDataSnapshot(value,budget={nodes:4096},depth=0){if(depth>32||budget.nodes<=0)return null;if(value===null||['string','number','boolean'].includes(typeof value))return value;if(value===undefined)return undefined;if(typeof value!=='object')return null;budget.nodes-=1;if(Array.isArray(value)){if(value.length>MAX_DIAGNOSTIC_COLLECTION)return null;const names=Object.getOwnPropertyNames(value);if(names.length!==value.length+1||names.some((name)=>name!=='length'&&!/^(?:0|[1-9]\d*)$/.test(name)))return null;if(Object.getOwnPropertySymbols(value).length>0)return null;const output=[];for(let index=0;index<value.length;index+=1){const descriptor=Object.getOwnPropertyDescriptor(value,String(index));if(!descriptor||!('value'in descriptor))return null;const item=plainDataSnapshot(descriptor.value,budget,depth+1);if(item===null&&descriptor.value!==null)return null;output.push(item);}return output;}if(!plain(value))return null;const names=Object.getOwnPropertyNames(value);if(names.length>MAX_DIAGNOSTIC_COLLECTION||Object.getOwnPropertySymbols(value).length>0)return null;const output={};for(const name of names){const descriptor=Object.getOwnPropertyDescriptor(value,name);if(!descriptor||!('value'in descriptor))return null;const item=plainDataSnapshot(descriptor.value,budget,depth+1);if(item===null&&descriptor.value!==null)return null;output[name]=item;}return output;}
function stableArchiveMerge(merge){if(!plain(merge))return merge;const stable={};for(const key of boundedOwnDataKeys(merge)??[]){if(key==='merged_at'||key==='provenance')continue;stable[key]=ownData(merge,key).value;}return stable;}
export function validatedArchiveSnapshot(value){const snapshot=plainDataSnapshot(value);if(!snapshot||!plain(snapshot))return null;const hash=ownData(snapshot,'record_hash').value;let hashVerified=false;if(hash!==undefined){if(typeof hash!=='string'||!/^[0-9a-f]{64}$/i.test(hash))return null;const imported=ownData(snapshot,'imported').value===true;const hashed=!imported&&plain(ownData(snapshot,'merge').value)?{...snapshot,merge:stableArchiveMerge(ownData(snapshot,'merge').value)}:snapshot;const omitted=imported?['record_hash','imported_at']:['record_hash','completed_at','timing'];hashVerified=diagnosticHashRecord(hashed,omitted)===hash;if(!hashVerified)return null;}const safeSnapshot=hashVerified&&Object.hasOwn(snapshot,'merge')&&!isValidMergeEvidence(snapshot.merge)?{...snapshot,merge:null}:snapshot;return{snapshot:safeSnapshot,hashVerified};}
function validateLifecycle(state,archived,suppliedDispatch,archiveVerified=false){
 if(!plain(state))return false;const run=ownData(state,'run_id');if(!run.ok||!isCanonicalRunId(run.value))return false;const importedField=ownData(state,'imported');const imported=archived&&importedField.ok&&importedField.value===true;if(importedField.ok&&importedField.value!==true)return false;const archiveHash=ownData(state,'record_hash').value;const modernArchiveHash=typeof archiveHash==='string'&&/^[0-9a-f]{64}$/i.test(archiveHash);if(archiveHash!==undefined&&!modernArchiveHash)return false;const generatedArchive=archived&&archiveVerified;const compatibleArchive=generatedArchive;
 for(const [key,allowed]of Object.entries(ENUMS)){const field=ownData(state,key);if(!field.ok&&imported&&key!=='status')continue;if(!field.ok&&compatibleArchive&&['stage','host','dispatch_state'].includes(key))continue;if(imported&&key==='mode'&&field.value==='import')continue;if(generatedArchive&&key==='mode'&&field.value==='patch')continue;if(imported&&key==='status'&&field.value==='unknown')continue;if(!field.ok&&key==='dispatch_state'&&(ownData(state,'version').value===2||ownData(state,'runtime_version').value===2)&&ENUMS.dispatch_state.has(suppliedDispatch))continue;if(!field.ok||!allowed.has(field.value))return false;}
 for(const key of ['tickets','receipts']){if(!Object.hasOwn(state,key))continue;const value=ownData(state,key).value;if(!Array.isArray(value)||value.length>MAX_DIAGNOSTIC_COLLECTION||!validArray(value,plain))return false;}
 if(Object.hasOwn(state,'expired_tickets')){const value=ownData(state,'expired_tickets').value;if(!Array.isArray(value)||value.length>MAX_DIAGNOSTIC_COLLECTION||!validArray(value,(v)=>identifier(v)))return false;}if(Object.hasOwn(state,'pending')&&!validArray(ownData(state,'pending').value,plain))return false;
 const tickets=(ownData(state,'tickets').value?.length??0)<=MAX_DIAGNOSTIC_COLLECTION?ownData(state,'tickets').value??[]:[];for(const ticket of tickets){const ticketStage=ownData(ticket,'stage_id').value;if(!identifier(ownData(ticket,'ticket_id').value))return false;if(ticketStage===undefined&&!generatedArchive)return false;if(ticketStage!==undefined&&!ENUMS.stage.has(ticketStage)&&!(generatedArchive&&/^stage-\d+$/.test(ticketStage)))return false;const role=ownData(ticket,'role').value;if(role===undefined&&!generatedArchive)return false;if(role!==undefined&&!TICKET_ROLES.has(role))return false;const attempt=ownData(ticket,'attempt').value;if(attempt!==undefined&&(!Number.isInteger(attempt)||attempt<1||attempt>MAX_DIAGNOSTIC_NUMBER))return false;const deadline=ownData(ticket,'deadline_at').value;if(deadline!==undefined&&strictIsoMs(deadline)===null)return false;}
 const receipts=(ownData(state,'receipts').value?.length??0)<=MAX_DIAGNOSTIC_COLLECTION?ownData(state,'receipts').value??[]:[];for(const receipt of receipts){if(!identifier(ownData(receipt,'ticket_id').value))return false;const receiptStatus=ownData(receipt,'status').value;if(receiptStatus===undefined&&!generatedArchive)return false;if(receiptStatus!==undefined&&!['passed','failed'].includes(receiptStatus))return false;const receiptTiming=ownData(receipt,'timing').value;if(receiptTiming!==undefined){if(!plain(receiptTiming))return false;for(const key of ['started_at','completed_at']){const value=ownData(receiptTiming,key).value;if(value!==undefined&&strictIsoMs(value)===null)return false;}const duration=ownData(receiptTiming,'duration_ms').value;if(duration!==undefined&&!boundedNumber(duration))return false;}}
 const gates=ownData(state,'gates').value;if(gates!==undefined&&gates!==null){if(!plain(gates))return false;const passed=ownData(gates,'passed').value;if(typeof passed!=='boolean')return false;const checks=ownData(gates,'checks').value;if(checks!==undefined&&(!plain(checks)||boundedOwnDataKeys(checks)===null))return false;const count=ownData(gates,'checks_count').value;if(count!==undefined&&!boundedNumber(count))return false;}
 const remediation=ownData(state,'remediation_route').value;if(remediation!==undefined){if(!plain(remediation)||!['test','production','test-production'].includes(ownData(remediation,'route').value))return false;const cycle=ownData(remediation,'cycle').value;if(cycle!==undefined&&!boundedNumber(cycle))return false;const testPaths=ownData(remediation,'test_paths').value;if(testPaths!==undefined&&!validArray(testPaths,(value)=>typeof value==='string'&&value.length<=2048))return false;}
 const preflight=ownData(state,'preflight').value;if(preflight!==undefined){if(!plain(preflight))return false;const answers=ownData(preflight,'answers').value;if(answers!==undefined&&!validArray(answers,plain))return false;const artifact=ownData(preflight,'artifact').value;if(artifact!==undefined){if(!plain(artifact))return false;for(const key of ['profiles','verification_profiles']){const value=ownData(artifact,key).value;if(value!==undefined&&!validArray(value,plain))return false;}}}
 const inputRequired=ownData(state,'input_required').value;if(inputRequired!==undefined){if(!plain(inputRequired))return false;const kind=ownData(inputRequired,'kind').value,questions=ownData(inputRequired,'questions').value,questionIds=ownData(inputRequired,'question_ids').value;if(kind!==undefined&&!['receipt_retry','execution_budget'].includes(kind))return false;if(questions!==undefined&&!validArray(questions,plain))return false;if(questionIds!==undefined&&!validArray(questionIds,identifier))return false;}
 const profiles=ownData(state,'profiles').value;if(profiles!==undefined&&!validArray(profiles,plain))return false;for(const key of ['claimed_paths','test_paths']){const paths=ownData(state,key).value;if(paths!==undefined&&!validArray(paths,(value)=>typeof value==='string'&&value.length<=2048))return false;}const verificationProfiles=ownData(state,'verification_profiles').value;if(verificationProfiles!==undefined&&!validArray(verificationProfiles,plain))return false;
 const attempts=ownData(state,'attempts').value;if(attempts!==undefined){const attemptKeys=boundedOwnDataKeys(attempts);if(!attemptKeys||attemptKeys.some((key)=>!identifier(key)))return false;for(const key of attemptKeys){const value=ownData(attempts,key).value;if(!Number.isInteger(value)||value<1||value>MAX_DIAGNOSTIC_NUMBER)return false;}}
 for(const key of ['retries_count','retry_count','regate_attempts','remediation_cycles']){const value=ownData(state,key).value;if(value!==undefined&&!boundedNumber(value))return false;}const inputHold=ownData(state,'input_hold').value;if(inputHold!==undefined){if(!plain(inputHold))return false;for(const key of ['question_count','questions_answered']){const value=ownData(inputHold,key).value;if(value!==undefined&&!boundedNumber(value))return false;}const ids=ownData(inputHold,'question_ids').value;if(ids!==undefined&&!validArray(ids,identifier))return false;}
 const timing=ownData(state,'timing').value;if(timing!==undefined){if(!plain(timing))return false;for(const key of ['raw_ms','test_ms','remote_ci_ms']){const value=ownData(timing,key).value;if(value!==undefined&&!boundedNumber(value))return false;}}
 if(archived){for(const key of ['created_at','completed_at','terminal_at']){const value=ownData(state,key).value;if(value!==undefined&&strictIsoMs(value)===null)return false;}const merge=ownData(state,'merge').value;if(merge!==undefined&&merge!==null&&!isValidMergeEvidence(merge)){if(!archiveVerified)return false;const keys=boundedOwnDataKeys(merge,1);const legacyUrl=keys?.length===1&&keys[0]==='url'?ownData(merge,'url').value:null;if(typeof legacyUrl!=='string'||legacyUrl.length===0||legacyUrl.length>2048)return false;try{const parsed=new URL(legacyUrl);if(parsed.protocol!=='https:'||parsed.username||parsed.password||parsed.hostname.toLowerCase()!=='github.com'||parsed.port)return false;}catch{return false;}}}return true;
}
function failedChecks(state){const gates=ownData(state,'gates').value,checks=ownData(gates,'checks').value;if(!plain(checks))return[];const found=[];for(const key of boundedOwnDataKeys(checks)??[]){const check=ownData(checks,key).value;if(!plain(check)||ownData(check,'passed').value!==false)continue;const raw=ownData(check,'id').value,id=identifier(raw)?raw:(identifier(key)?key:null);if(id)found.push(id);}return[...new Set(found)].sort().slice(0,MAX_FAILED_CHECKS);}
function dispatchState(state,supplied){if(ENUMS.dispatch_state.has(supplied))return supplied;const stored=ownData(state,'dispatch_state').value;return ENUMS.dispatch_state.has(stored)?stored:'none';}
function timing(state,archived){if(archived){const raw=ownData(ownData(state,'timing').value,'raw_ms').value;if(boundedNumber(raw))return{available:true,source:'archived_timing_provenance',duration_ms:raw};const start=strictIsoMs(ownData(state,'created_at').value),end=strictIsoMs(ownData(state,'completed_at').value??ownData(state,'terminal_at').value);if(start!==null&&end!==null&&end>=start)return{available:true,source:'durable_run_timestamps',duration_ms:end-start};}const tickets=ownData(state,'tickets').value,receipts=ownData(state,'receipts').value;if(Array.isArray(tickets)&&tickets.length<=MAX_DIAGNOSTIC_COLLECTION&&Array.isArray(receipts)&&receipts.length<=MAX_DIAGNOSTIC_COLLECTION){const stages=new Map();for(const ticket of tickets){const ticketId=ownData(ticket,'ticket_id').value,stageId=ownData(ticket,'stage_id').value;if(identifier(ticketId)&&ENUMS.stage.has(stageId))stages.set(ticketId,stageId);}let selected=null;for(const receipt of receipts){const ticketId=ownData(receipt,'ticket_id').value,receiptTiming=ownData(receipt,'timing').value,start=strictIsoMs(ownData(receiptTiming,'started_at').value),end=strictIsoMs(ownData(receiptTiming,'completed_at').value),stageId=stages.get(ticketId)??(typeof ticketId==='string'?ticketId.split(':')[1]:null);if(start!==null&&end!==null&&end>=start&&stageId===ownData(state,'stage').value)selected={available:true,source:'receipt_timestamps',stage_id:stageId,duration_ms:end-start};}if(selected)return selected;}return{available:false,source:'unavailable'};}
function classify(state,archived,corrupt,suppliedDispatch,archiveVerified){if(corrupt)return'corrupt_state';if(!state)return archived?'incomplete_record':'inactive';if(!validateLifecycle(state,archived,suppliedDispatch,archiveVerified))return archived?'incomplete_record':'corrupt_state';if(archived&&ownData(state,'imported').value===true)return'legacy_record';const status=ownData(state,'status').value,stage=ownData(state,'stage').value,gatesPassed=ownData(ownData(state,'gates').value,'passed').value,dispatch=dispatchState(state,suppliedDispatch);if(!archived&&dispatch==='error')return'dispatch_evidence_unreadable';if(status==='gating')return'gating';if(status==='blocked'&&(stage==='gates'||gatesPassed===false))return'gate_failed';if(status==='blocked'&&stage==='merge'&&gatesPassed===true)return'shipping_hold';if(status==='blocked')return'blocked';if(status==='shipping')return'shipping';if(status==='input_required'){const kind=ownData(ownData(state,'input_required').value,'kind').value;if(kind==='receipt_retry')return'receipt_retry_input_required';if(kind==='execution_budget')return'execution_budget_input_required';return'preflight_input_required';}if(!archived&&['completed','aborted'].includes(status)&&typeof ownData(state,'base_branch').value==='string'&&typeof ownData(state,'branch').value==='string'&&ownData(ownData(state,'checkout_cleanup').value,'status').value!=='returned')return'cleanup_pending';if(status==='completed')return'completed';if(status==='aborted')return'aborted';if(dispatch==='stopped')return'dispatch_stopped';if(dispatch==='pending'||dispatch==='needs-redispatch')return'dispatch_pending';if(dispatch==='live')return'dispatch_live';return'stage_active';}
export function projectRunDiagnostic(state,options={}){try{const archived=options.archived===true;let inspected=state,archiveVerified=options.archiveVerified===true;if(archived&&options.trustedSnapshot!==true){const validated=validatedArchiveSnapshot(state);if(!validated)inspected=null;else{inspected=validated.snapshot;archiveVerified=validated.hashVerified;}}const code=classify(inspected,archived,options.corrupt===true,options.dispatchState,archiveVerified);const[next_safe_action,recovery_rationale]=DEFINITIONS[code]??DEFINITIONS.incomplete_record;return{reason_code:code,next_safe_action,recovery_rationale,failed_checks:code==='corrupt_state'||code==='incomplete_record'?[]:failedChecks(inspected),stage_timing:code==='corrupt_state'||code==='incomplete_record'?{available:false,source:'unavailable'}:timing(inspected,archived)};}catch{const code=options.archived===true?'incomplete_record':'corrupt_state';const[next_safe_action,recovery_rationale]=DEFINITIONS[code];return{reason_code:code,next_safe_action,recovery_rationale,failed_checks:[],stage_timing:{available:false,source:'unavailable'}};}}
export const DIAGNOSTIC_REASON_CODES=Object.freeze(Object.keys(DEFINITIONS));
