import { execFileSync } from 'node:child_process';
import { access, mkdtemp, mkdir, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { recordReceipt, startRun } from '../lib/runtime/service.js';
import { runtimePaths } from '../lib/runtime/paths.js';
import { atomicWriteJson } from '../lib/runtime/storage.js';

// D2 (red-test strict, side effects): ecosystem runners routinely write
// artifacts during execution — a package manager resolving Gemfile.lock,
// generated bytecode — and the old blanket tree-stability rejection walled the
// retry behind an unclaimed-write rejection with a misleading external-writer
// hint. Now: files the command CREATED (absent from the attested tree) are
// removed — deletion exactly restores the attested tree — and recorded in the
// sealed observation; a command that rewrites a PRE-EXISTING file refuses with
// the real cause, because content restoration would clobber concurrent work.
// Cleanup runs before any verdict check, so even a green run leaves the tree
// clean.

const cleanups = [];
afterEach(async () => {
  await Promise.all(cleanups.splice(0).map((dir) => rm(dir, { recursive: true, force: true })));
});

function git(cwd, ...args) {
  return execFileSync('git', args, { cwd, encoding: 'utf8' }).trim();
}

async function exists(file) {
  try {
    await access(file);
    return true;
  } catch {
    return false;
  }
}

async function project({ files = {}, template }) {
  const dir = await mkdtemp(path.join(tmpdir(), 'ape-red-fx-'));
  cleanups.push(dir);
  await mkdir(path.join(dir, 'src'));
  await mkdir(path.join(dir, 'tests'));
  await writeFile(path.join(dir, 'src', 'value.js'), 'export const value = 1;\n');
  for (const [file, content] of Object.entries(files)) {
    await writeFile(path.join(dir, file), content);
  }
  git(dir, 'init', '-q');
  git(dir, 'config', 'user.email', 'ape@example.test');
  git(dir, 'config', 'user.name', 'APE Test');
  git(dir, 'add', '.');
  git(dir, 'commit', '-qm', 'baseline');
  await atomicWriteJson(runtimePaths(dir).config, {
    shipping: { auto_merge: false, provider: 'github', required_remote_checks: false },
    test_commands: { full: 'node --test', targeted_template: template },
  });
  return dir;
}

function startInput() {
  return {
    objective: 'Exercise red-test side-effect handling',
    mode: 'phase',
    lane: 'fast',
    host: 'codex',
    claimed_paths: ['src/value.js'],
    test_paths: ['tests/value.test.js'],
    requirements: [],
    risk_triggers: [],
    behavioral: true,
    hooks_trusted: true,
    subagents_available: true,
    explicit_invocation: true,
  };
}

function rawReceipt(ticket) {
  return {
    ticket_id: ticket.ticket_id,
    status: 'passed',
    agent_identity: `agent-${ticket.role}`,
    tests: [{ command: 'self-reported', passed: false, exit_code: 1, duration_ms: 1 }],
    findings: [],
    evidence: { verdict: 'pass' },
    timing: {
      started_at: ticket.issued_at,
      completed_at: new Date(Date.parse(ticket.issued_at) + 10).toISOString(),
      duration_ms: 10,
    },
  };
}

async function admit(dir) {
  const started = await startRun(dir, startInput());
  expect(started.ok).toBe(true);
  const ticket = started.run.tickets[0];
  expect(ticket.required_checks).toContain('red-test');
  await writeFile(path.join(dir, 'tests', 'value.test.js'), 'throw new Error("red");\n');
  return recordReceipt(dir, rawReceipt(ticket));
}

describe('red-test execution side-effect artifacts (D2)', () => {
  it('removes a created lockfile-style artifact, admits red, and records the restore', async () => {
    const dir = await project({
      files: {
        'lock-writer.mjs':
          'import { writeFileSync } from "node:fs";\nwriteFileSync("Gemfile.lock", "GEM\\n  fake (1.0)\\n");\nprocess.exit(1);\n',
      },
      template: 'node lock-writer.mjs {paths}',
    });
    const result = await admit(dir);
    expect(result.ok).toBe(true);
    expect(result.receipt.evidence.red_test).toMatchObject({
      observed: true,
      passed: false,
      restored_artifacts: ['Gemfile.lock'],
      tree_sha: result.receipt.head_tree_sha,
    });
    // The artifact is gone from disk: the retry's recomputed diff can never
    // hit the unclaimed-write wall, and the attested tree is exactly restored.
    expect(await exists(path.join(dir, 'Gemfile.lock'))).toBe(false);
  });

  it('refuses when the command rewrites a pre-existing file, naming the real cause', async () => {
    const dir = await project({
      files: {
        'rewriter.mjs':
          'import { writeFileSync } from "node:fs";\nwriteFileSync("src/value.js", "export const value = 999;\\n");\nprocess.exit(1);\n',
      },
      template: 'node rewriter.mjs {paths}',
    });
    const result = await admit(dir);
    expect(result).toMatchObject({ ok: false, rejected: true });
    const message = result.errors.join(' ');
    expect(message).toMatch(/modified pre-existing files \(src\/value\.js\)/);
    expect(message).toMatch(/committed or gitignored/);
    // The old framing blamed "an external or orphaned writer" — the cause is
    // the executed command, and the message must say so.
    expect(message).not.toMatch(/external|orphaned/i);
  });

  it('cleans a created artifact even when the run exits green (restore precedes verdict)', async () => {
    const dir = await project({
      files: {
        'green-writer.mjs':
          'import { writeFileSync } from "node:fs";\nwriteFileSync("artifact.tmp", "generated\\n");\nprocess.exit(0);\n',
      },
      template: 'node green-writer.mjs {paths}',
    });
    const result = await admit(dir);
    expect(result).toMatchObject({ ok: false, rejected: true });
    expect(result.errors.join(' ')).toMatch(/red phase was not observed/);
    // The refusal is the green verdict, not tree instability — and the
    // artifact was still cleaned up, so the refused receipt leaves the tree
    // exactly as the test writer attested it.
    expect(await exists(path.join(dir, 'artifact.tmp'))).toBe(false);
  });

  it('removes a created artifact in a created subdirectory (bytecode-cache shape)', async () => {
    const dir = await project({
      files: {
        'cache-writer.mjs':
          'import { mkdirSync, writeFileSync } from "node:fs";\nmkdirSync("__pycache__", { recursive: true });\nwriteFileSync("__pycache__/mod.pyc", "bytecode\\n");\nprocess.exit(1);\n',
      },
      template: 'node cache-writer.mjs {paths}',
    });
    const result = await admit(dir);
    expect(result.ok).toBe(true);
    expect(result.receipt.evidence.red_test.restored_artifacts).toEqual(['__pycache__/mod.pyc']);
    expect(await exists(path.join(dir, '__pycache__', 'mod.pyc'))).toBe(false);
  });
});
